docs: add contribution instructions
fingerprintjs/botd pull request #33
Opened 2021-09-07 17:31 UTC by makma

Fixes #32 
- add contribution instructions

2021-09-10 13:48 UTC, Romchela requested changes

2021-09-13 11:26 UTC, makma commented on playground/index.html
> + <script async src="../dist/botd.js"></script>
Oh, I see, I haven't realized we use the playground for demo purposes. Yes, the first option is the simplest and the most transparent. Will do.

2021-09-13 11:47 UTC, makma commented on playground/index.html
> + <script async src="../dist/botd.js"></script>
Fixed: https://github.com/fingerprintjs/botd/pull/33/commits/555ac76bd35b9705327b5c3c540c53e78eea25df

2021-09-13 11:52 UTC, makma commented on contributing.md
> +3. See what's will get into the NPM package, make sure it contains the distributive files and no excess files.
Sure, my bad, thx, fixed: https://github.com/fingerprintjs/botd/pull/33/commits/f54aaf59d71d99863b8b3f19056c2f9c56ca45db

2021-09-13 11:53 UTC, Romchela approved these changes

2021-09-13 11:54 UTC, Romchela approved these changes

2021-09-13 11:59 UTC, merged